openapi: 3.1.0
info:
  title: Petstore
  summary: This API stores data about available pets 
  description: The API enables users to view detailed information about a specific pet store and its available pets. The API can be used by pet owners, pet adoption agencies, and anyone looking for information about pets in a particular area.
  contact: 
    name": APIMatic,
    url: https://www.sdks.io/contact,
    email: support@sdks.io"
  version: '1.0.0'
jsonSchemaDialect: https://json-schema.org/draft/2020-12/schema
servers:
- url: https://src8wr32cg.api.quickmocker.com
  variables: {}
paths:
  /pets:
    post:
      tags:
      - pets
      summary: createPets
      description: Create a pet and key characteristics
      operationId: createPets
      parameters: []
      requestBody:
        description: A single Pet object used to create a new Pet
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
            example:
              id: 12345
              name: Indiana
              tag: dog
      responses:
        '201':
          description: Null response
          headers: {}
          content: {}
        default:
          description: unexpected error
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      deprecated: false
    get:
      tags:
      - pets
      summary: listPets
      description: List all pets
      operationId: listPets
      parameters:
      - name: limit
        in: query
        description: How many items to return at one time (max 100)
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          contentEncoding: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              content:
                text/plain:
                  schema:
                    type: string
                    description: A link to the next page of responses
                    contentMediaType: text/plain
          content:
            application/json:
              schema:
                maxItems: 100
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
                description: ''
                contentMediaType: application/json
        default:
          description: unexpected error
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      deprecated: false
    parameters: []
  /pets/{petId}:
    get:
      tags:
      - pets
      summary: showPetById
      description: Info for a specific pet
      operationId: showPetById
      parameters:
      - name: petId
        in: path
        description: The id of the pet to retrieve
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: Expected response to a valid request
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      deprecated: false
    parameters: []
components:
  schemas:
    Pet:
      title: Pet
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          contentEncoding: int64
          example: 1234
        name:
          type: string
          example:  Fido
        tag:
          type: string
          example: dog
    Error:
      title: Error
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          contentEncoding: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      description: bearer token security
      scheme: bearer
security:
- bearerAuth: []
tags:
- name: pets
  description: ''
