"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PetToJSON = exports.PetFromJSONTyped = exports.PetFromJSON = exports.instanceOfPet = void 0;
const runtime_1 = require("../runtime");
/**
 * Check if a given object implements the Pet interface.
 */
function instanceOfPet(value) {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    return isInstance;
}
exports.instanceOfPet = instanceOfPet;
function PetFromJSON(json) {
    return PetFromJSONTyped(json, false);
}
exports.PetFromJSON = PetFromJSON;
function PetFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'tag': !(0, runtime_1.exists)(json, 'tag') ? undefined : json['tag'],
    };
}
exports.PetFromJSONTyped = PetFromJSONTyped;
function PetToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'id': value.id,
        'name': value.name,
        'tag': value.tag,
    };
}
exports.PetToJSON = PetToJSON;
