/**
 * PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface Pet {
  id: bigint;
  name: string;
  tag?: string;
}

export const petSchema: Schema<Pet> = object({
  id: ['id', bigint()],
  name: ['name', string()],
  tag: ['tag', optional(string())],
});
